openapi: '3.0.2'
info:
  title: EIDO Conveyance Subscribe and Notify schema
  version: '1.0.1'
servers:
  - url: http://localhost/IncidentData
paths:
  /ent:
    get:
      description: Stub to keep OpenAPI happy, not to be used. These objects are exchanged over a WebSocket as documented in NENA-STA-024.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                 - $ref: '#/components/schemas/subscriberMessage'
                 - $ref: '#/components/schemas/notifierMessage'

components:
  schemas:

    subscriberMessage:
      oneOf:
        - $ref: '#/components/schemas/subscribeObject'
        - $ref: '#/components/schemas/unsubscribeObject'
        - $ref: '#/components/schemas/eventResponseObject'
        - $ref: '#/components/schemas/terminateResponseObject'
    notifierMessage:
      oneOf:
        - $ref: '#/components/schemas/subscribeResponseObject'
        - $ref: '#/components/schemas/unsubscribeResponseObject'
        - $ref: '#/components/schemas/responseObject'
        - $ref: '#/components/schemas/eventObject'
        - $ref: '#/components/schemas/terminateObject'

    subscribeObject:
      type: object
      properties:
        subscribe:
          type: object
          required:
            - requestId
          properties:
            requestId:
              type: string
              description: An ID generated by the subscriber that will be returned by the notifier in its response to the request.
            requestType:
              type: string
              description: Type of request, e.g., "EIDO". Required for a new subscription, i.e., if no subscriptionId provided.
              enum:
                - EIDO
            requestSubType:
              type: string
              description: For a request type of "EIDO", subtype MUST be one of "single", "new", or "resource".
              enum:
                - single
                - new
                - resource
            requestAccepts:
              type: string
              description: The MIME type associated with the requestType and the major versions thereof
            qualFilter:
              type: string
              description: qualFilter. A filter MUST NOT be specified if an incidentId is specified.
            minRate:
              type: integer
              description: Number of seconds after the last notification after which a notification must be sent.
            maxRate:
              type: integer
              description: Minimum time in seconds to wait between notifications which is the maximum rate at which notifications are sent
            subscriptionId:
              type: string
              description: The subscriptionId previously returned by the service.
            incidentId:
              type: string
              description: Subscribe to a specific incident.
            expires:
              type: integer
              description: Number of seconds after which the subscription shall expire.

    subscribeResponseObject:
      type: object
      properties:
        subscribeResponse:
          type: object
          required:
            - requestId
            - statusCode
            - statusText
          properties:
            requestId:
              type: string
              description: The ID provided by the subscriber.
            subscriptionId:
              type: string
              description: If successful, the globally unique identifier for the subscription.
            minRate:
              type: integer
            maxRate:
              type: integer
            expires:
              type: integer
              description: Subscription period in seconds relative to the notifier’s establishment or renewal of the subscription.
            statusCode:
              description: The statusCode element is a 3-digit integer result code of the attempt to understand and satisfy the request
              type: integer
              enum: 
                - 200
                - 400
                - 403
                - 404
                - 406
                - 413
                - 481
                - 500
                - 503
            statusText:
              description: The statusText provides a short textual description related to the  statusCode.
              type: string
            qualFilterEvalPeriod:
              type: integer
              description: If qualFilter specified, a positive integer specifying the requested number of seconds between qualFilter evaluations.

    unsubscribeObject:
      type: object
      properties:
        unsubscribe:
          type: object
          required:
            - requestId
            - subscriptionId
          properties:
            requestId:
              type: string
              description: An ID generated by the subscriber that will be returned by the notifier in its response to the request.
            subscriptionId:
              type: string
              description: The subscriptionId sent by the service.

    unsubscribeResponseObject:
      type: object
      properties:
        unsubscribeResponse:
          type: object
          required:
            - requestId
            - subscriptionId
            - statusCode
            - statusText
          properties:
            requestId:
              type: string
              description: The ID generated by the subscriber.
            subscriptionId:
              type: string
              description: Globally unique identifier for the subscription.
            statusCode:
              description: The statusCode element is a 3-digit integer result code of the attempt to understand and satisfy the request
              type: integer
              enum:
                - 200
                - 400
                - 413
                - 481
                - 500
                - 503
            statusText:
              type: string
              description: The statusText is intended to provide information related to the statusCode.
    
    responseObject:
      type: object
      properties:
        response:
          type: object
          required:
            - requestId
            - statusCode
            - statusText
          properties:
            requestId:
              type: string
              description: The ID provided by the subscriber.
            statusCode:
              type: integer
              enum: 
                - 501
            statusText:
              type: string
              enum: 
                - "Not implemented"
    eventObject:
      type: object
      properties:
        event:
          type: object
          required:
            - subscriptionId
            - transactionId
          properties:
            subscriptionId:
              type: string
              description: Subscription to which this event belongs.
            transactionId:
              type: string
              description: A GUID used to identify a notification for acknowledgement.
            notification:
              type: array
              items:
                type: object #EIDO

    eventResponseObject:
      type: object
      properties:
        eventResponse:
          type: object
          required:
            - transactionId
            - statusCode
            - statusText
          properties:
            transactionId:
              type: string
              description: GUID used to identify a transaction for acknowledgement.
            statusCode:
              description: Status code of response according to the request
              type: integer
              enum:
                - 200
                - 400
                - 404
                - 413
                - 481
                - 500
                - 501
                - 503
            statusText:
              type: string
              description: The statusText is intended to provide information related to the statusCode.
              
    terminateObject:
      type: object
      properties:
        terminate:
          type: object
          required:
            - requestId
            - subscriptionId
          properties:
            requestId:
              type: string
              description: An ID generated by the notifier that will be returned by the subscriber in its response to the request.
            subscriptionId:
              type: string
              description: Subscription being terminated.

    terminateResponseObject:
      type: object
      properties:
        terminateResponse:
          type: object
          required:
            - requestId
            - subscriptionId
            - statusCode
            - statusText
          properties:
            requestId:
              type: string
              description: The ID generated by the notifier.
            subscriptionId:
              type: string
              description: Subscription being terminated.
            statusCode:
              description: The statusCode element is a 3-digit integer result code of the attempt to understand and satisfy the request
              type: integer
              enum:
                - 200
                - 400
                - 481
                - 500
                - 501
                - 503
            statusText:
              type: string
              description: The statusText is intended to provide information related to the statusCode.

